name: BitShares
description: BitShares 2.0 is an industrial-grade financial smart contract platform.
url: https://bitshares.org

collections:
    content:
        output: true
    technologies:
        output: true

defaults:
    - scope:
          path: content/en
      values:
          lang: en



    - scope:
          type: technologies
      values:
          layout: technology
          priority: 100

    - scope:
          path: technologies/en
      values:
          lang: en



    - scope:
          type: posts
      values:
          layout: post

    - scope:
          path: _posts/en
      values:
          lang: en


excerpt_separator: <!--more-->


permalink: /blog/:year/:month/:day/:title/

# Theme Settings
theme_reading_time: true
