collections:
    technology:
        output: true

defaults:
    - scope:
          type: technology
      values:
          layout: technology
          priority: 100
    - scope:
          type: posts
      values:
          layout: post
