collections:
    content:
        output: true

defaults:
    - scope:
          type: posts
      values:
          layout: post

    - scope:
          path: content/en
      values:
          lang: en

    - scope:
          path: content/en/technology
      values:
          layout: technology
          priority: 100

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

# Theme Settings
theme_reading_time: 		true
